name: Downstream Release
on:
  release:
    types: [published]

jobs:
  downstream-release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: SakifSurur/downstream-silver-spork
          event-type: release
          client-payload: '{"version": "$GITHUB_REF"}'
